USE [master]
GO

/****** Object:  Database [StationeryDB]    Script Date: 26/07/2024 16:27:42 ******/
CREATE DATABASE [StationeryDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StationeryDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\StationeryDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StationeryDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\StationeryDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StationeryDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StationeryDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StationeryDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StationeryDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StationeryDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StationeryDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [StationeryDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StationeryDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StationeryDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StationeryDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StationeryDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StationeryDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StationeryDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StationeryDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StationeryDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StationeryDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [StationeryDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StationeryDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StationeryDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StationeryDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StationeryDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StationeryDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StationeryDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StationeryDB] SET RECOVERY FULL 
GO

ALTER DATABASE [StationeryDB] SET  MULTI_USER 
GO

ALTER DATABASE [StationeryDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StationeryDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StationeryDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StationeryDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StationeryDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StationeryDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [StationeryDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [StationeryDB] SET  READ_WRITE 
GO

